#!/usr/bin/env python3
"""Organize flat POSCAR/conf.lmp files into named composition subfolders.

Takes the flat files generated by ``generate_selected_composition_structures.py``
inside ``selected_compositions/`` and copies each pair into a named subfolder::

    POSCAR__id09__He040__MgSiO3_24fu__360atoms  -->  24MgSiO3_40He/POSCAR
    conf.lmp__id09__He040__MgSiO3_24fu__360atoms --> 24MgSiO3_40He/conf.lmp

The folder naming convention ``{n_MgSiO3}MgSiO3_{n_He}He`` matches the
reference layout used in the 72_MgSiO3__360_atoms__and_He directory.

Usage:
    python3 organize_selected_compositions.py [--dry-run]
"""

import os
import re
import shutil
import sys
from typing import List
from typing import Tuple


BASE_DIR: str = os.path.dirname(os.path.abspath(__file__))
SELECTED_DIR: str = os.path.join(BASE_DIR, "selected_compositions")

POSCAR_PATTERN = re.compile(
    r"^POSCAR__id\d+__He(\d+)__MgSiO3_(\d+)fu__\d+atoms$"
)
CONF_LMP_PATTERN = re.compile(
    r"^conf\.lmp__id\d+__He(\d+)__MgSiO3_(\d+)fu__\d+atoms$"
)


def find_poscar_files(selected_dir: str) -> List[str]:
    """Find all flat POSCAR files in the selected_compositions directory.

    Args:
        selected_dir: Path to the selected_compositions directory.

    Returns:
        Sorted list of POSCAR filenames (basenames only).
    """
    return sorted(
        f for f in os.listdir(selected_dir)
        if POSCAR_PATTERN.match(f)
    )


def parse_composition(poscar_filename: str) -> Tuple[int, int]:
    """Extract n_He and n_MgSiO3 from a POSCAR filename.

    Args:
        poscar_filename: Basename matching the POSCAR naming convention.

    Returns:
        Tuple of (n_He, n_MgSiO3).

    Raises:
        ValueError: If the filename does not match the expected pattern.
    """
    match = POSCAR_PATTERN.match(poscar_filename)
    if match is None:
        raise ValueError(f"Cannot parse composition from: {poscar_filename}")
    n_he = int(match.group(1))
    n_mgsio3 = int(match.group(2))
    return n_he, n_mgsio3


def get_conf_lmp_filename(poscar_filename: str) -> str:
    """Derive the corresponding conf.lmp filename from a POSCAR filename.

    Args:
        poscar_filename: Basename of the POSCAR file.

    Returns:
        Expected conf.lmp filename.
    """
    return poscar_filename.replace("POSCAR__", "conf.lmp__", 1)


def folder_name(n_mgsio3: int, n_he: int) -> str:
    """Build the subfolder name for a given composition.

    Args:
        n_mgsio3: Number of MgSiO3 formula units.
        n_he: Number of He atoms.

    Returns:
        Folder name like ``24MgSiO3_40He``.
    """
    return f"{n_mgsio3}MgSiO3_{n_he}He"


def main() -> None:
    """Organize flat files into named composition subfolders."""
    dry_run = "--dry-run" in sys.argv

    if not os.path.isdir(SELECTED_DIR):
        print(f"Error: {SELECTED_DIR} not found.")
        sys.exit(1)

    poscar_files = find_poscar_files(SELECTED_DIR)
    if not poscar_files:
        print("No POSCAR files found matching the expected pattern.")
        sys.exit(1)

    print(f"Selected compositions dir: {SELECTED_DIR}")
    print(f"Found {len(poscar_files)} POSCAR files")
    if dry_run:
        print("*** DRY RUN — no files will be copied ***")
    print("-" * 60)

    created = 0
    for poscar_filename in poscar_files:
        n_he, n_mgsio3 = parse_composition(poscar_filename)
        conf_lmp_filename = get_conf_lmp_filename(poscar_filename)
        dest_folder = folder_name(n_mgsio3, n_he)
        dest_path = os.path.join(SELECTED_DIR, dest_folder)

        poscar_src = os.path.join(SELECTED_DIR, poscar_filename)
        conf_lmp_src = os.path.join(SELECTED_DIR, conf_lmp_filename)

        if not os.path.isfile(conf_lmp_src):
            print(f"[WARN] Missing conf.lmp for {poscar_filename}, skipping.")
            continue

        action = "DRY-RUN" if dry_run else "CREATE"
        print(f"[{action}] {dest_folder}/")
        print(f"         POSCAR   <- {poscar_filename}")
        print(f"         conf.lmp <- {conf_lmp_filename}")

        if not dry_run:
            os.makedirs(dest_path, exist_ok=True)
            shutil.copy2(poscar_src, os.path.join(dest_path, "POSCAR"))
            shutil.copy2(conf_lmp_src, os.path.join(dest_path, "conf.lmp"))
        created += 1

    print("-" * 60)
    print(f"Compositions organized: {created}")


if __name__ == "__main__":
    main()
